site:
  title: "Modern Mathematical Methods"
  author: "Danny Caballero"
  description: "A modern, open-source course in mathematical methods for physics and astrophysics."
  logo: "static/images/logo.png"
  favicon: "static/images/favicon.ico"
  theme:
    default: dark
    light: light
    dark: dark
  language: "en"
  github_url: "https://github.com/open-physics-ed-org/oer-forge"
  
toc:
  - title: "Home"
    menu: true
    file: index.md
  - title: "Docs"
    menu: true
    children:
      - title: "Installation"
        file: docs/installation.md
        menu: false
      - title: "Build System"
        file: docs/build_system.md
        menu: false
      - title: "OER Forge Logos"
        file: docs/logos.md
        menu: false
  - title: "Dev"
    menu: true
    children: 
      - title: "Punchlist"
        menu: true
        file: dev/punchlist.md 
  - title: "WCAG"
    menu: true
    children:
      - title: "Main JS"
        file: docs/main_js.md
        menu: false
    children:
      - title: "Reports"
        menu: false
        children:
          - title: "Report 1"
            file: wcag/reports/report1.md
            menu: false
          - title: "Report 2"
            file: wcag/reports/report2.md
            menu: false
  - title: "Sample Materials"
    menu: true
    children:
      - title: "Sample Course Description"
        file: sample/course_description.md
        menu: false
    children:
      - title: "Overture: What is Classical Physics?"
        file: sample/notebooks/01_start.ipynb
        menu: false
      - title: "Introduction to Classical Mechanics"
        file: sample/notebooks/01_notes.ipynb
        menu: false
      - title: "Mathematical Preliminaries"
        file: sample/02_notes.ipynb
        menu: false
      - title: "Critical Points; Phase Space; Trajectories"
        file: sample/07_notes.ipynb
        menu: false
      - title: "Metropolis Activity"
        file: sample/activity-metropolis.docx
        menu: false
      - title: "Notes on Phase Space"
        file: sample/notes-phase_space.docx
        menu: false
  - title: "About"
    menu: true
    file: about.md

footer:
  text: |
    Made with tons of ☕️  and lots of ❤️ for students and educators everywhere. | Built with <a href="https://github.com/OER-Forge/">OER Forge</a>

static:
  images:
    - path: static/images/
      description: "Site-wide images and figures"
  css:
    - path: static/css/
      description: "Custom CSS files"
  js:
    - path: static/js/
      description: "Custom JavaScript files"
  templates:
    - path: static/templates/
      description: "HTML templates"
  themes:
    - path: static/themes/
      description: "Theme files"

# Metadata for automated build and export
build:
  outputs:
    - html
    - pdf
    - docx
    - md
    - tex
    - jupyter
    - ppt
    - ipynb
  output_dir: _build/
  docs_dir: docs/
