site:
  title: "Modern Mathematical Methods"
  author: "Danny Caballero"
  description: "A modern, open-source course in mathematical methods for physics and astrophysics."
  logo: "static/images/logo.png"
  favicon: "static/images/favicon.ico"
  theme:
    default: dark
    light: light
    dark: dark
  language: "en"
  github_url: "https://github.com/open-physics-ed-org/oer-forge"
  
toc:
  - title: "Home"
    menu: true
    file: index.md
  - title: "Punchlist"
    menu: true
    file: punchlist.md
  - title: "Build System"
    menu: true
    file: build_system.md
  - title: "Docs"
    menu: true
    children:
      - title: "Installation"
        file: docs/installation.md
        menu: false
      - title: "Main JS"
        file: docs/main_js.md
        menu: false

footer:
  text: 'Made in Michigan with tons of ☕️  and lots of ❤️ for students and educators everywhere.
    <br>
    <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" style="display:inline-block; vertical-align:middle; margin-top:0.5em;">
      <img alt="Creative Commons License" style="border-width:0; height:22px; margin-right:0.3em; vertical-align:middle;" src="https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png" />
    </a><a href="https://open-physics-ed-org.github.io/">openphysicsed.org</a>'

static:
  images:
    - path: static/images/
      description: "Site-wide images and figures"
  css:
    - path: static/css/
      description: "Custom CSS files"
  js:
    - path: static/js/
      description: "Custom JavaScript files"
  templates:
    - path: static/templates/
      description: "HTML templates"
  themes:
    - path: static/themes/
      description: "Theme files"

# Metadata for automated build and export
build:
  outputs:
    - html
    - pdf
    - docx
    - md
    - tex
    - jupyter
    - ppt
    - ipynb
  output_dir: _build/
  docs_dir: docs/
