site:
  title: "Test Site"
  author: "Test Author"
  description: "Testing TOC parsing."

toc:
  - title: "Home"
    menu: true
    file: index.md
  - title: "Docs"
    menu: true
    children:
      - title: "Install"
        file: docs/install.md
        menu: false
      - title: "Build"
        file: docs/build.md
        menu: false
  - title: "Dev"
    menu: true
    children:
      - title: "Punchlist"
        menu: true
        file: dev/punchlist.md
  - title: "Autogen Section"
    menu: false
    children:
      - title: "Autogen Child"
        menu: false
        # No file, should be autogen
  - title: "Duplicate"
    menu: true
    file: index.md
  - title: "Missing File"
    menu: true
    file: missing.md
