site: {
  id
  site_title
  site_subtitle
  site_url
  site_license
  site_logo
  site_favicon
  site_theme_light
  site_theme_dark
  site_theme_default
  site_footer
}

toc: {
  toc_id
  toc_filename
  toc_title
  toc_filetype
  toc_level
  toc_automated_build
}

page: {
  page_id
  page_filename
  page_title
  page_filetype
  page_convert_*
  page_built_ok_*
  page_wcag_ok_*
  page_filename_*
  page_level
  page_toc_id
}

page_images: {
  id
  image_page_id
  image_filename
  image_remote
  image_type
}

# Relationships
page.page_toc_id -> toc.toc_id
page_images.image_page_id -> page.page_id